# Dockerfile
FROM python:3.14

# Instalar dependencias de machine learning con versiones específicas
RUN pip install --no-cache-dir \
    joblib==1.5.3 \
    numpy==2.4.2 \
    pandas==3.0.1 \
    pathlib==1.0.1 \
    python-dateutil==2.9.0.post0 \
    six==1.17.0 \
    typing==3.7.4.3 \